using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Stock_Management_System
{
    public static class Tools
    {
        // Function that takes an email address as a string and checks that it's a valid email address
        public static bool validEmail(string email)
        {
            if (string.IsNullOrWhiteSpace(email)) { return false; }
            string[] parts = email.Split('@');
            if (parts.Length != 2) { return false; }
            string domain = parts[1];
            string[] domainParts = domain.Split('.');
            if (!(domainParts.Length >= 2)) { return false; }
            return true;
        }

        // Function to retrieve an entity ID from an entity identifier generated by overideen .ToString() functions
        public static bool getEntityId(string identifier, out int id)
        {
            string[] firstSplit = identifier.Split("(");
            string[] secondSplit = firstSplit[1].Split(")");
            if (!int.TryParse(secondSplit[0], out int result))
            {
                id = -1;
                return false;
            }
            id = result;
            return true;
        }
    }
}
